HunterPie/HunterPie

HunterPie.Core/Client/Configuration/Overlay/TelemetricsWidgetConfig.cs, HunterPie.Core/Client/Configuration/OverlayConfig.cs, HunterPie.Core/Domain/Process/IProcessManager.cs, HunterPie.Core/Events/ProcessEventArgs.cs, HunterPie.Core/Game/Context.cs, HunterPie.Core/Game/Data/IGameStrings.cs, HunterPie.Core/Game/GameManager.cs, HunterPie.Core/Game/IGame.cs, HunterPie.Core/Game/World/Entities/MHWMonster.cs, HunterPie.Core/Game/World/Entities/MHWPlayer.cs, HunterPie.Core/Game/World/MHWContext.cs, HunterPie.Core/Game/World/MHWGame.cs, HunterPie.Core/HunterPie.Core.csproj, HunterPie.Core/System/ProcessManager.cs, HunterPie.Core/System/ProcessManagerEventArgs.cs, HunterPie.Core/System/Windows/MHWProcessManager.cs, HunterPie.Core/System/Windows/WindowsProcessManager.cs, HunterPie.UI/HunterPie.UI.csproj.user, HunterPie.UI/Overlay/Widgets/Metrics/View/TelemetricsView.xaml, HunterPie.UI/Overlay/Widgets/Metrics/View/TelemetricsView.xaml.cs, HunterPie.UI/Overlay/Widgets/Metrics/ViewModel/TelemetricsViewModel.cs, HunterPie/App.xaml.cs, HunterPie/MainWindow.xaml.cs
=> Feat(UI): Added Metrics Widget

HunterPie/Languages/ko-kr.xml
This is preliminary ko-kr localization for HunterPie's future update.
If there is new changes, I'll add commit.
Added tanslations for new strings
Fixed several strings
=> Update ko-kr for v.2.0.21

HunterPie/Languages/it-it.xml
Also fixed some inconsistent part names.
Do note that palico and dango abilities might not reflect the in-game translation 100% correctly.
=> Add all missing translation in Italian localization.

HunterPie/Languages/de-de.xml
Might get a revision regarding 2 untranslated strings soon (tm)
=> de-de update for 2.0.22

HunterPie/Languages/ko-kr.xml
Hi, Haato.
I modified skill name that was mistranslated.
Can you please update live version?
=> [koKR] Fix a wrong skill name

HunterPie.Core/HunterPie.Core.csproj, HunterPie.UI/Controls/Buttons/Keybinding.xaml, HunterPie.UI/Controls/Buttons/Keybinding.xaml.cs, HunterPie.UI/HunterPie.UI.csproj, HunterPie/Properties/AssemblyInfo.cs
=> Feat(UI): Redesign Keybinding control

HunterPie.UI/Architecture/Converters/CurrentValueToWidthConverter.cs
=> Fix(UI): Fixed Training Dojo state bar going back and forth

HunterPie.Core.Tests/HunterPie.Core.Tests.csproj, HunterPie.Core/Address/Map/Internal/AddressMapParserExtensions.cs, HunterPie.Core/HunterPie.Core.csproj
=> Fix(Core): Fix duplicate map keys crash

HunterPie.Core/Game/Data/MonsterData.cs, HunterPie.Core/Game/Data/Schemas/MonsterPartSchema.cs, HunterPie.Core/Game/World/Definitions/MHWTenderizeInfoStructure.cs, HunterPie.Core/Game/World/Entities/MHWMonster.cs, HunterPie.Core/Game/World/Entities/MHWMonsterPart.cs, HunterPie.Core/HunterPie.Core.csproj, HunterPie.UI/HunterPie.UI.csproj, HunterPie.UI/Overlay/Widgets/Monster/MonsterPartContextHandler.cs, HunterPie.UI/Overlay/Widgets/Monster/Views/BossMonsterPartView.xaml, HunterPie/Properties/AssemblyInfo.cs
=> Feat(Core|UI): Add tenderize info

Docs/_posts/2022-06-14-damage-meter-widget.md, Docs/_posts/2022-06-14-update-v2.1.0.md, Docs/_posts/2022-06-16-specialized-tools-widget.md, HunterPie.UI/Overlay/Widgets/SpecializedTools/Views/SpecializedToolView.xaml
=> Docs: Add v2.1.0 documentation

HunterPie/Languages/de-de.xml
More to come, if we can log the stage data too
gonna finish the game today or so
=> Feat(Localization): Add Sunbreak monsters in german

HunterPie.Core/HunterPie.Core.csproj, HunterPie.UI/HunterPie.UI.csproj, HunterPie/Game/World/Data/MonsterData.xml, HunterPie/Languages/en-us.xml, HunterPie/Properties/AssemblyInfo.cs
=> Fix(Localization): Missing monster part names

HunterPie.Core/Game/Rise/Definitions/MHREnrageStructure.cs, HunterPie.Core/Game/Rise/Entities/MHRMonster.cs, HunterPie.Core/HunterPie.Core.csproj, HunterPie.UI/HunterPie.UI.csproj, HunterPie/Properties/AssemblyInfo.cs
=> Fix(Core): Fixed Enrage structure for MHR

HunterPie/Languages/fr-fr.xml
Most of World's strings are taken from V1
=> v2.2.0 French translation

HunterPie.Core/HunterPie.Core.csproj, HunterPie.UI/HunterPie.UI.csproj, HunterPie.UI/Overlay/Widgets/Abnormality/AbnormalityContextHandler.cs, HunterPie/Game/Rise/Data/AbnormalityData.xml, HunterPie/Properties/AssemblyInfo.cs
- Fixed `Chain Crit` offset
- Fixed `The Frenzy` buildup not displaying properly
=> Hotfix(Data): Fix chain crit offset

HunterPie.Core/Game/Rise/Definitions/MHRChatMessageStructure.cs, HunterPie.Core/Game/Rise/Definitions/MHRSubmarineItemStructure.cs, HunterPie.Core/Game/Rise/Entities/Activities/MHRSubmarine.cs, HunterPie.Core/Game/Rise/Entities/MHRPlayer.cs, HunterPie.Core/Game/Rise/Entities/Party/MHRParty.cs, HunterPie.Core/HunterPie.Core.csproj, HunterPie.UI/HunterPie.UI.csproj, HunterPie.UI/Overlay/Widgets/Chat/ChatWidgetContextHandler.cs, HunterPie.UI/Overlay/Widgets/Chat/Presentation/MemberIndexToColorConverter.cs, HunterPie.UI/Overlay/Widgets/Chat/ViewModels/ChatElementViewModel.cs, HunterPie.UI/Overlay/Widgets/Chat/ViewModels/MockChatViewModel.cs, HunterPie.UI/Overlay/Widgets/Chat/Views/ChatStringView.xaml, HunterPie/Properties/AssemblyInfo.cs
- Fixes #151 
- Fixes chat widget
=> Fix(Core|UI): v2.3.0 fixes

HunterPie.Core/Game/Data/MonsterData.cs, HunterPie.Core/Game/Data/Schemas/MonsterDataSchema.cs, HunterPie.Core/Game/World/Entities/MHWMonster.cs, HunterPie/Game/World/Data/MonsterData.xml
Adds support for : 
- Show the capture indicator and threshold in the Monster bar
- Show the monster weaknesses
Implementation details: 
- For the MHW capture data, I migrated the data from the V1 MonsterData.xml into the new one.
- For the Monster weaknesses, I only populated the array (the weakness data was already there).
=> Feat(Core): Add MHW capture data and weaknesses

HunterPie.Native/Core/Entities/damage.h, HunterPie.Native/Core/Managers/Damage/manager.h, HunterPie.Native/Core/Server/Handlers/Damage/DamageMessageHandler.h, HunterPie.Native/Core/Server/Handlers/Initialize/InitializationMessageHandler.h, HunterPie.Native/Core/Server/Handlers/MessageHandler.h, HunterPie.Native/Core/Server/IPCService.h, HunterPie.Native/Core/Server/Models/Messages.h, HunterPie.Native/Games/Rise/Common/Monster.h, HunterPie.Native/Games/Rise/Damage/damage.h, HunterPie.Native/Games/Rise/Damage/hooks.h, HunterPie.Native/Games/Rise/Utils/RiseUtils.h
Use nested namespace declarations since C++ 17 to reduce nested namespaces.
=> Chore(Native): Use nested namespace declarations

HunterPie/Internal/Initializers/CustomThemeInitializer.cs
=> Fix(Core): Loading incorrect theme settings

HunterPie/Internal/Initializers/CustomThemeInitializer.cs
Changed File.Exists to Directory.Exists
=> Fix(Core): Fix to check valid theme path

HunterPie.UI/Controls/Settings/Custom/AbnormalityTrayList.xaml.cs, HunterPie.UI/Dialog/DialogView.xaml, HunterPie/Languages/de-de.xml, HunterPie/Languages/en-us.xml, HunterPie/Languages/es-mx.xml, HunterPie/Languages/fr-fr.xml, HunterPie/Languages/it-it.xml, HunterPie/Languages/ja-jp.xml, HunterPie/Languages/ko-kr.xml, HunterPie/Languages/ru-ru.xml, HunterPie/Languages/zh-cn.xml, HunterPie/Languages/zh-tw.xml, HunterPie/MainWindow.xaml.cs, HunterPie/Update/UpdateUseCase.cs
Also, delete deprecated localization entries
=> Feat(Localization):Added localization for dialog windows

HunterPie.Core/Domain/Process/IProcessManager.cs, HunterPie.Core/System/ProcessManagerEventArgs.cs, HunterPie.Core/System/Windows/WindowsProcessManager.cs, HunterPie/App.xaml.cs, HunterPie/Languages/en-us.xml, HunterPie/Languages/zh-cn.xml
Also renamed the `EnableNativeModule` option into "Enable native module".
=> Chore(Core): Show hint on disabling native module when MHW crashes

HunterPie.UI/Controls/Settings/SettingElementHost.xaml, HunterPie/Languages/en-us.xml, HunterPie/Languages/ko-kr.xml
Added support localization for (Requires Restart) string.
Added new strings for ko-kr.xml
=> Feat(Localization): Update for v2.4.0

HunterPie.Core/API/Entities/ChangePasswordRequest.cs, HunterPie.Core/API/Entities/ErrorCode.cs, HunterPie.Core/API/Entities/PasswordChangeResponse.cs, HunterPie.Core/API/Entities/PasswordResetRequest.cs, HunterPie.Core/API/PoogieApi.cs, HunterPie.Core/HunterPie.Core.csproj, HunterPie.UI/HunterPie.UI.csproj, HunterPie.UI/Resources/Icons.xaml, HunterPie.UI/Resources/Styles.xaml, HunterPie/GUI/Parts/Account/ViewModels/AccountLoginFlowViewModel.cs, HunterPie/GUI/Parts/Account/ViewModels/AccountPasswordResetFlowViewModel.cs, HunterPie/GUI/Parts/Account/Views/AccountLoginFlowView.xaml, HunterPie/GUI/Parts/Account/Views/AccountLoginFlowView.xaml.cs, HunterPie/GUI/Parts/Account/Views/AccountPasswordResetFlowView.xaml, HunterPie/GUI/Parts/Account/Views/AccountPasswordResetFlowView.xaml.cs, HunterPie/HunterPie.csproj.user, HunterPie/Languages/en-us.xml, HunterPie/Properties/AssemblyInfo.cs
- Added password reset flow
depends on https://github.com/Haato3o/Poogie/pull/24
fixes #243
=> Feat(Account): Add forgot password button

HunterPie/Game/Rise/Data/AbnormalityData.xml, HunterPie/Languages/en-us.xml, HunterPie/Languages/ko-kr.xml
Sorry for the icon not implemented.
=> Feat(Core): Added Bloodblight debuff abnormality

HunterPie/Languages/en-us.xml, HunterPie/Languages/ko-kr.xml
=> Feat(Loc): Add a missing string for ko-kr

HunterPie/Game/Rise/Data/AbnormalityData.xml
Adrenaline Rush's AttackUp timer.
Chain Crit's icon changed Orange to Salmon for in-game matching.
=> Feat(Data): Added Adrenaline Rush

HunterPie.Core/Game/Entity/Player/IAbnormality.cs, HunterPie.Integrations/Datasources/Common/Entity/Player/CommonAbnormality.cs, HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Player/MHRConsumableAbnormality.cs, HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Player/MHRDebuffAbnormality.cs, HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Player/MHRSongAbnormality.cs, HunterPie.Integrations/Datasources/MonsterHunterWorld/Entity/Player/MHWAbnormality.cs, HunterPie.UI/Overlay/Widgets/Abnormality/AbnormalityContextHandler.cs, HunterPie.UI/Overlay/Widgets/Abnormality/ViewModel/AbnormalityViewModel.cs
Can use abnormality name in theme.
=> Feat(Core|UI): Added abnormality name to AbnormalityViewModel

HunterPie.Core/HunterPie.Core.csproj, HunterPie.Integrations/Datasources/MonsterHunterWorld/Entity/Player/MHWPlayer.cs, HunterPie.Integrations/HunterPie.Integrations.csproj, HunterPie.UI/HunterPie.UI.csproj, HunterPie/AssemblyInfo.cs
=> Fix(Core): Wrong player gets removed from party when someone leaves

HunterPie.Integrations/Datasources/MonsterHunterRise/Definitions/MHRPartyMemberData.cs, HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Party/MHRParty.cs, HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Party/MHRPartyMember.cs, HunterPie.Integrations/HunterPie.Integrations.csproj, HunterPie.UI/HunterPie.UI.csproj, HunterPie/AssemblyInfo.cs
=> Fix(Core): Duplicate character names breaks MHR party

HunterPie.Core/HunterPie.Core.csproj, HunterPie.Integrations/HunterPie.Integrations.csproj, HunterPie.Memory/HunterPie.Memory.csproj, HunterPie.UI/HunterPie.UI.csproj, HunterPie/Integrations/Poogie/PoogieProvider.cs, HunterPie/Properties/AssemblyInfo.cs
- It is really hard to know if multiple exceptions happened in the same session
- Added unique identifier that's generated every session to make it easier to debug crashes and exceptions
=> Feat(Core): Generate session UUID

HunterPie.Core/Networking/Http/HttpClientBuilder.cs, HunterPie.UI/Controls/Buttons/Keybinding.xaml.cs, HunterPie/App.xaml.cs, HunterPie/Update/UpdateUseCase.cs
=> Fix(Core|UI): Common exceptions

HunterPie/Game/Rise/Data/AbnormalityData.xml
Timer until the next bird arrives
=> Feat(Data): Added support for Spiribird's Call skill

HunterPie/Game/Rise/Data/AbnormalityData.xml
=> Feat(Data): Added support for Heaven Sent skill

README.md
=> Fix: Lines Badge

HunterPie.Core/HunterPie.Core.csproj, HunterPie.Integrations/Datasources/MonsterHunterWorld/Entity/Player/MHWPlayer.cs, HunterPie.Integrations/Datasources/MonsterHunterWorld/Entity/Player/Weapons/MHWChargeBlade.cs, HunterPie.Integrations/Datasources/MonsterHunterWorld/Entity/Player/Weapons/MHWDualBlades.cs, HunterPie.Integrations/Datasources/MonsterHunterWorld/Entity/Player/Weapons/MHWInsectGlaive.cs, HunterPie.Integrations/Datasources/MonsterHunterWorld/Entity/Player/Weapons/MHWMeleeWeapon.cs, HunterPie.Integrations/Datasources/MonsterHunterWorld/Utils/MHWGameUtils.cs, HunterPie.Integrations/HunterPie.Integrations.csproj, HunterPie.UI/HunterPie.UI.csproj, HunterPie.UI/Overlay/Widgets/Player/PlayerHudWidgetContextHandler.cs, HunterPie.UI/Overlay/Widgets/Player/Views/WeaponSharpnessView.xaml, HunterPie/Properties/AssemblyInfo.cs
- HunterPie now calculates the current sharpness level, the one calculated by the game was troublesome since it is not calculated in real time
- Fixed Handicraft buff calculation
=> Hotfix(Core): Calculate sharpness level based on current sharpness

HunterPie.Integrations/Datasources/MonsterHunterWorld/Entity/Player/Weapons/MHWChargeBlade.cs, HunterPie.Integrations/HunterPie.Integrations.csproj, HunterPie.Native/HunterPie.Native.vcxproj, HunterPie.UI/HunterPie.UI.csproj, HunterPie/Properties/AssemblyInfo.cs
=> Feat(Core): Adjust charge blade power prolonger

HunterPie/UI/SideBar/Views/SideBarView.xaml, HunterPie/UI/SideBar/Views/SideBarView.xaml.cs
Fix SideBar,Simplified logic, no need to call events frequently
=> Fix(UI): Fix SideBar scaling for high DPI displays

HunterPie.Core/HunterPie.Core.csproj, HunterPie.Integrations/HunterPie.Integrations.csproj, HunterPie.UI/HunterPie.UI.csproj, HunterPie.UI/Overlay/Widgets/Activities/View/SteamFuelView.xaml, HunterPie.UI/Overlay/Widgets/Activities/ViewModel/MockActivitiesViewModel.cs, HunterPie/Properties/AssemblyInfo.cs
=> Fix(UI): Fixed steamworks progress not calculating bar width correctly

HunterPie.Core/Domain/Mapper/Internal/XmlNodeToMonsterDefinitionMapper.cs, HunterPie.Core/HunterPie.Core.csproj, HunterPie.Integrations/HunterPie.Integrations.csproj, HunterPie.UI/Controls/Settings/Monsters/Builders/MonsterGlobalConfigurationViewModelBuilder.cs, HunterPie.UI/Controls/Settings/Monsters/Builders/MonsterPartsViewModelBuilder.cs, HunterPie.UI/HunterPie.UI.csproj, HunterPie/Game/Rise/Data/MonsterData.xml, HunterPie/Game/World/Data/MonsterData.xml, HunterPie/Properties/AssemblyInfo.cs
=> Hotfix(UI): Duplicate monster part ids

HunterPie.Core/Client/Configuration/Enums/GameType.cs, HunterPie.Core/HunterPie.Core.csproj, HunterPie.DI/HunterPie.DI.csproj, HunterPie.Integrations/HunterPie.Integrations.csproj, HunterPie.Platforms/HunterPie.Platforms.csproj, HunterPie.UI/Controls/Buttons/Button.xaml, HunterPie.UI/HunterPie.UI.csproj, HunterPie.UI/Resources/Icons.xaml, HunterPie/Features/Analytics/Services/AnalyticsService.cs, HunterPie/Properties/AssemblyInfo.cs, HunterPie/UI/Home/Services/HomeService.cs, HunterPie/UI/Home/Views/HomeView.xaml, HunterPie/UI/Home/Views/SupportedGameView.xaml, HunterPie/UI/SideBar/Views/SideBarView.xaml
=> feat(ui):  home game buttons

HunterPie.Core/HunterPie.Core.csproj, HunterPie.DI/HunterPie.DI.csproj, HunterPie.Integrations/HunterPie.Integrations.csproj, HunterPie.Platforms/HunterPie.Platforms.csproj, HunterPie.UI/HunterPie.UI.csproj, HunterPie/Properties/AssemblyInfo.cs, HunterPie/Usecases/VerifyHunterPiePathUseCase.cs
Fixes [e39c53c](https://github.com/HunterPie/HunterPie/pull/577/commits/e39c53c9c66057f2d2bf1a18f4e6a63b10351d84)
=> hotfix(core): false positive when using HunterPie in an OneDrive env

HunterPie.Core/HunterPie.Core.csproj, HunterPie.DI/HunterPie.DI.csproj, HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Enemy/MHRMonster.cs, HunterPie.Integrations/HunterPie.Integrations.csproj, HunterPie.Platforms/HunterPie.Platforms.csproj, HunterPie.UI/Architecture/Assets/GetAsset.cs, HunterPie.UI/Architecture/Images/ImageMergerService.cs, HunterPie.UI/HunterPie.UI.csproj, HunterPie.UI/Overlay/Widgets/Abnormality/AbnormalityWidgetContextHandler.cs, HunterPie.UI/Overlay/Widgets/Monster/MonsterContextHandler.cs, HunterPie.UI/Overlay/Widgets/Monster/MonsterWidgetContextHandler.cs, HunterPie.UI/Overlay/Widgets/Monster/ViewModels/BossMonsterViewModel.cs, HunterPie/Properties/AssemblyInfo.cs
=> Fix(UI): fix GDI generic error

HunterPie.Core/Game/Entity/Enemy/IMonster.cs, HunterPie.Core/Game/Entity/Enemy/VariantType.cs, HunterPie.Core/HunterPie.Core.csproj, HunterPie.DI/HunterPie.DI.csproj, HunterPie.Integrations/Datasources/Common/Entity/Enemy/CommonMonster.cs, HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Enemy/MHRMonster.cs, HunterPie.Integrations/Datasources/MonsterHunterWilds/Entity/Enemy/MHWildsMonster.cs, HunterPie.Integrations/Datasources/MonsterHunterWorld/Entity/Enemy/MHWMonster.cs, HunterPie.Integrations/HunterPie.Integrations.csproj, HunterPie.Platforms/HunterPie.Platforms.csproj, HunterPie.UI/HunterPie.UI.csproj, HunterPie.UI/Overlay/Widgets/Monster/MonsterContextHandler.cs, HunterPie.UI/Overlay/Widgets/Monster/Presentation/MonsterVariantBrushConverter.cs, HunterPie.UI/Overlay/Widgets/Monster/ViewModels/BossMonsterViewModel.cs, HunterPie.UI/Overlay/Widgets/Monster/ViewModels/MockMonstersViewModel.cs, HunterPie.UI/Overlay/Widgets/Monster/Views/BossMonsterView.xaml, HunterPie.UI/Overlay/Widgets/Monster/Views/CollapsedBossMonsterView.xaml, HunterPie/Properties/AssemblyInfo.cs
=> feat(core): add monster variant indicator

HunterPie.Core/Converters/ObservableConverter.cs
Hello 
Small PR to handle gracefully new games (for the future). If the enum isn't known, it will set the value to null instead of crashing
=> Handle gracefully unknown new games

HunterPie.Core/HunterPie.Core.csproj, HunterPie.DI/HunterPie.DI.csproj, HunterPie.Integrations/Datasources/MonsterHunterWilds/Entity/Game/MHWildsGame.cs, HunterPie.Integrations/HunterPie.Integrations.csproj, HunterPie.Platforms/HunterPie.Platforms.csproj, HunterPie.UI/HunterPie.UI.csproj, HunterPie/Properties/AssemblyInfo.cs
=> fix(core): fixed mhwilds clock calculation

HunterPie.Core/Client/Configuration/Overlay/ClockWidgetConfig.cs, HunterPie.Core/HunterPie.Core.csproj, HunterPie.DI/HunterPie.DI.csproj, HunterPie.Integrations/Datasources/MonsterHunterWilds/Definitions/World/MHWildsMoon.cs, HunterPie.Integrations/Datasources/MonsterHunterWilds/Definitions/World/MHWildsMoonControllers.cs, HunterPie.Integrations/Datasources/MonsterHunterWilds/Entity/Game/MHWildsGame.cs, HunterPie.Integrations/Datasources/MonsterHunterWilds/Entity/Game/Moon/MoonPhase.cs, HunterPie.Integrations/HunterPie.Integrations.csproj, HunterPie.Platforms/HunterPie.Platforms.csproj, HunterPie.UI/Architecture/Converters/Game/MoonPhaseToIconConverter.cs, HunterPie.UI/Architecture/Converters/Game/MoonPhaseToStringConverter.cs, HunterPie.UI/HunterPie.UI.csproj, HunterPie.UI/HunterPie.UI.csproj.user, HunterPie.UI/Overlay/Widgets/Clock/ClockWidgetContextHandler.cs, HunterPie.UI/Overlay/Widgets/Clock/ViewModels/ClockViewModel.cs, HunterPie.UI/Overlay/Widgets/Clock/ViewModels/MoonViewModel.cs, HunterPie.UI/Overlay/Widgets/Clock/Views/ClockView.xaml, HunterPie.UI/Overlay/Widgets/Clock/Views/ClockView.xaml.cs, HunterPie.UI/Overlay/Widgets/Clock/Views/MoonView.xaml, HunterPie.UI/Overlay/Widgets/Clock/Views/MoonView.xaml.cs, HunterPie.UI/Resources/Icons/General.xaml, HunterPie/Address/MonsterHunterWilds.1.1.1.0.map, HunterPie/App.xaml, HunterPie/Features/Debug/ClockWidgetMocker.cs, HunterPie/Properties/AssemblyInfo.cs
=> feat(core): add moon phases tracking

HunterPie.Core/Client/Configuration/Overlay/DamageMeterWidgetConfig.cs, HunterPie.Core/HunterPie.Core.csproj, HunterPie.DI/HunterPie.DI.csproj, HunterPie.Integrations/Datasources/MonsterHunterWilds/Entity/Party/MHWildsPartyMember.cs, HunterPie.Integrations/HunterPie.Integrations.csproj, HunterPie.Platforms/HunterPie.Platforms.csproj, HunterPie.UI/HunterPie.UI.csproj, HunterPie.UI/Overlay/Widgets/Damage/Controllers/DamageMeterControllerV2.cs, HunterPie.UI/Overlay/Widgets/Damage/Helpers/PlayerConfigHelper.cs, HunterPie/Properties/AssemblyInfo.cs
=> feat(core):  add supporter hunters damage tracking
